include:
  # Left keyboard - always peripheral
  - board: nice_nano
    shield: charybdis_left

  # Standalone mode - right is central
  - board: nice_nano
    shield: charybdis_right_standalone
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y

  # Dongle mode
  - board: nice_nano
    shield: charybdis_right_dongle

  - board: seeeduino_xiao_ble
    shield: prospector_dongle prospector_adapter
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y

  # Settings reset for both board types
  - board: nice_nano
    shield: settings_reset

  - board: seeeduino_xiao_ble
    shield: settings_reset

  # Tester Pro Micro
  - board: nice_nano
    shield: tester_pro_micro
    format: bt
